
server:
  port: 7090 // specify port
  servlet:
      context-path: /auth // add context and configure it into gateway server yml
jwt:
  auth:
    converter:
      resource-id: authenticationClientId
keycloak:
  realm: bisky-music
  domain: keycloak.codewithbisky.com
  adminClientId: admin-cli
  adminClientSecret: your_secret
  client: authenticationClientId
  urls:
    auth: https://${keycloak.domain}
spring:
  profile:
    active: production
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${keycloak.domain}/realms/${keycloak.realm}